### ISSUE TITLE
Print Layout to be created for Sales Invoice

### ISSUE THREAD

**Issue by revant** [revant/kiratplastics_erpnext#10]
**Requirement Number :** 9
**Project Module :** Invoice
**Type :** Customization
**Description :** Print Layout to be created for Sales Invoice (Specimen supplied)
**Note :** "Custom Field- Part Name in doctype Item Customer Detail, New Print Format 4in1 (Working Title)

**Comment by gaurav-naik** [comment]
Added new Print format 'KP Sales Invoice'. https://github.com/revant/kiratplastics_erpnext/commit/d41947b87d1502aeea68491987f45e4e9d6fe6f8
