### ISSUE TITLE
Items allowed in the invoice should be filtered based on Customer

### ISSUE THREAD

**Issue by revant** [revant/kiratplastics_erpnext#14]
**Requirement Number :** 10
**Project Module :** Invoice
**Type :** Configuration
**Description :** Items allowed in the invoice should be filtered based on Customer
**Note :** Code to filter Item list in Sales Invoice Item.
Code to disallow selection of item by barcode if the item's customer does not match the customer selected in the invoice.

**Comment by gaurav-naik** [comment]
https://github.com/revant/kiratplastics_erpnext/commit/b53aee71130aa8d6ae2b858887e93070d8cecc97
