### ISSUE TITLE
Associate Excise master with Item master

### ISSUE THREAD

**Issue by revant** [revant/kiratplastics_erpnext#2]
**Requirement Number :** 2
**Project Module :** Tax
**Type :** Data
**Description :** Associate Excise master with Item master
**Note :** Excise App

**Comment by revant** [comment]
https://github.com/revant/excise_erpnext/issues/6

**Comment by gaurav-naik** [comment]
https://github.com/revant/kiratplastics_erpnext/commit/65e8796dcdddfa602879068ebf7172b2f051832c
