### ISSUE TITLE
Sales Invoice: Freight and Packaging: KP Settings

### ISSUE THREAD

**Issue by gaurav-naik** [revant/kiratplastics_erpnext#24]
Add fields in KP Settings to set default accounts for freight and packaging.
Sales Invoice Custom Script: Pull accounts from KP settings and set in rows to be injected in Taxes and Charges.

**Comment by revant** [comment]
https://github.com/revant/kiratplastics_erpnext/commit/5bca6add1441a0584751e41a33d404c01676dc24
