### ISSUE TITLE
Add item excise price field to enter a custom price only for excise calculation (Note: Item excise price is a price of the product on which the excise duty will be calculated using the excise duty rate)

### ISSUE THREAD

**Issue by revant** [revant/kiratplastics_erpnext#5]
**Requirement Number :** 4
**Project Module :** Item
**Type :** Configuration
**Description :** Add item excise price field to enter a custom price only for excise calculation (Note: Item excise price is a price of the product on which the excise duty will be calculated using the excise duty rate)
**Note :** "Custom field Excise Price in Item DocType.

**Comment by revant** [comment]
https://github.com/revant/excise_erpnext/issues/5

**Comment by gaurav-naik** [comment]
Related Issue #2
