### ISSUE TITLE
Choose price list based on Invoice type. Alternately, set rate of items 0 by default if type is Challan or Sample.

### ISSUE THREAD

**Issue by revant** [revant/kiratplastics_erpnext#7]
**Requirement Number :** 6
**Project Module :** Invoice
**Type :** Customization
**Description :** Choose price list based on Invoice type. Alternately, set rate of items 0 by default if type is Challan or Sample.
**Note :** Create new Price List entry for zero-value items.
Add Item Price entries for each item with rate = 0 under the new Price List.
Code Change : In Sales Invoice, add code to set appropriate Price List automatically when Invoice Type is selected.

**Comment by gaurav-naik** [comment]
Reference Issue #6

**Comment by revant** [comment]
https://github.com/revant/kiratplastics_erpnext/commit/272d6ed74d0e2544c683b95817167200a786f481
